### ISSUE TITLE
Install new multi-alloc routine

### ISSUE THREAD

**Issue by smajee** [cabouman/mbircone#10]
Install new multi-alloc routine:
https://github.com/cabouman/C-code/blob/main/src/allocate.c

**Comment by dyang37** [comment]
This is not done. In C code we are still using the old memory alloc code.
Is the new multi-alloc routine more memory efficient?

**Comment by cabouman** [comment]
Yes, we should use the newest multi-alloc routine.
The newest multi-alloc routines should be in this repository. 
https://github.com/cabouman/C-code

**Comment by dyang37** [comment]
fix in PR #56
