### ISSUE TITLE
Signature Changes to 'recon' and 'project'

### ISSUE THREAD

**Issue by bommaritom** [cabouman/mbircone#107]
Hi all,

I have prepared a set of slides to discuss the required changes needed to the signatures of 'recon' and 'project' in order to implement laminography as a wrapper on top of mbircone.

The short changelog goes like this:

- **cone3D.py**: Modify ``recon`` and ``project``, and their auxiliary functions ``auto_image_size`` and ``create_sino_param_dict``.

- **Downstream effects**: Modify ``mace.py``, ``mace_4D.py``, and ``mace_4D_fast.py``.

To cover all these changes, I have prepared a presentation of 16 slides in total (this is still long). 9 of these slides concern the first bullet point above, and 7 concern the second bullet point. If I have been meticulous enough, the update should map exactly to these slides. I also have a separate, longer .pptx document, documenting and justifying my decisions. 

If 16 slides is too many; maybe we would want to break this down into steps. For instance, Prof. Bouman has mentioned talking to Diyu about the mace* files; if we could remove the dependencies there, then this particular update would be smaller. In that case, we would just discuss the 7 slides concerning the mace* files.

I have attached the slides to this issue:

[Changelog.pptx](https://github.com/cabouman/mbircone/files/10290915/Changelog.pptx)
[Detailed Changelog.pptx](https://github.com/cabouman/mbircone/files/10290916/Detailed.Changelog.pptx)

**Comment by bommaritom** [comment]
Update : 

The above changes are now implemented in `marco/dev`. 

The branch `quick_signature_changes` was a previous implementation. It is now completely deprecated. It may be deleted.

**Comment by dyang37** [comment]
Thanks Marco! I'll test the changes tomorrow.
Regards,
Diyu
________________________________

**Comment by bommaritom** [comment]
Just a note, in testing the changes I came across the errors mentioned in #109, so you might want to look at that first.

**Comment by bommaritom** [comment]
Maybe after you look at #109, we could merge the new master with those fixes in it into marco/dev and then test?

**Comment by dyang37** [comment]
Sure that sounds good.
I have not updated mace functions to align with the recent interface changes. Therefore I might also need to modify it. After that maybe we could both test the changes, merge it, and start looking at issue #107.
Diyu
________________________________
