### ISSUE TITLE
Bug in resinstall_conda_environmenet.sh

### ISSUE THREAD

**Issue by dyang37** [cabouman/mbircone#138]
It seems that the latest update (commit 99f9854f54fc62898252ef9203dbd33b5f2f087d) to the dev script does not quite work. The conda environment is not deactivated properly. See the error message below:
![Screen Shot 2023-07-06 at 11 12 13 AM](https://github.com/cabouman/mbircone/assets/7671736/25e102f3-b24b-486c-bf9b-c448738a150a)

**Fix: Replace "echo conda deactivate" with "conda deactivate" in resinstall_conda_environmenet.sh solves the issue.**

**Comment by gbuzzard** [comment]
Ok. Go ahead and make the fix, test, and make a pr.

**Comment by dyang37** [comment]
This is merged in PR #139 .
