### ISSUE TITLE
Design and develop multi-node MACE 4D interface and functionality

### ISSUE THREAD

**Issue by dyang37** [cabouman/mbircone#29]
- Design MACE 4D interface based on MACE 3D and python dask interface. Get group agreement on the interface design.
- Design and implement multi-node functionality inside MACE 4D.
- Produce good MACE 4D reconstructions on the following 4D dataset:
  1. simulated 4D dataset: bottle cap data. We have already reproduced Soumendu's results on the 4D bottle cap data. Next we need to:
    a). Make 4D phantom sharper by increasing the contrast.
    b). Make sure that default parameters result in good 4D MACE reconstruction.
  2. real dataset: 4D vial dataset. Here's the road map:
    a) Reproduce Soumendu's 4D MACE results.
    b) Make sure that default parameters result in good 4D MACE reconstruction.
- Test multi-node MACE on different machines/clusters. Here are the cluster types that are available for testing:
  1. Local cluster (personal computer).
  2. SLURM (Purdue brown cluster).
  3. SGE cluster (Lilly cluster).
  The goal is that we want MACE 4D reconstruction to work on different clusters with minimal modifications on the user side. Ideally user should be able to switch from one cluster option to another by changing one single line in a configuration file (for example, change SLURM to SGE).

**Comment by cabouman** [comment]
I'm closing this since we have an initial implementation of a DASK wrapper.
