### ISSUE TITLE
Add laminography functionality

### ISSUE THREAD

**Issue by cabouman** [cabouman/mbircone#95]
Marco, you can take the lead on creating a new laminography branch that is based on the mbircone with ROR control.

Diyu, you will need to help Marco delete some of the binaries that accidentally got committed to the old laminography branch.

**Comment by dyang37** [comment]
> Marco, you can take the lead on creating a new laminography branch that is based on the mbircone with ROR control.
> 
> Diyu, you will need to help Marco delete some of the binaries that accidentally got committed to the old laminography branch.

Got it. @bommaritom Marco, please let me know once you finish with all the updates. We'll then need to do a purge of the binary files from the branch.

**Comment by cabouman** [comment]
This has been completed. Hooray!
